apiVersion: apps/v1
kind: Deployment
metadata:
  name: section-enged-deployment
spec:
  selector:
    matchLabels:
      app: section-enged
  template:
    metadata:
      labels:
        app: section-enged
    spec:
      containers:
        - name: section-enged
          imagePullPolicy: IfNotPresent
